### ISSUE TITLE
video en demo "hetzelfde"

### ISSUE THREAD

**Issue by maartenmarx** [deboradum/bachelorThesis#13]
Hi @deboradum , laat je nog even weten als de video en de demo nu zo ongeveer hetzelfdfe zijn? Dan maak ik een blogpostje met de 2 links en stuur dat naar de mensen die we uitgenodigd hadden. 

Heb jij een vragenlijstje voor ze? Allicht in een Google form, dan kan ik dat meteen meesturen. Een paar vragen, allicht gewoon alleen "tops" en verbeterpunten, om te zoregn dat je wat respons hebt.

groetjes
maarten

**Comment by deboradum** [comment]
@maartenmarx 
Ik heb Maik een mailtje gestuurd, maar nog geen reactie. Hij is vast druk deze laatste periode. 

Ik ben nu op werk, maar zal eind van de dag een vragenlijst opstellen en naar je sturen! Ook zal ik Maik dan een reminder sturen. 

Oja: Ik heb gister de eerste versie van de thesis geupload op canvas, maar was hem vergeten hier te sturen.
https://www.overleaf.com/read/ffgqmgpqwfyh#90ebac

Het meeste is geschreven, op een aantal background information stukjes na die ik deze week doe. 
Ik denk dat ik een aantal dingetjes, o.a. de related work, nog even na wil kijken en verbeteren.

Groetjes Pepijn

**Comment by maartenmarx** [comment]
Hi @deboradum ,

Mooi begin je scriptie!! Je kan er nog best flink aan schaven in mijn optiek. Je wilt die 8 wel binnenhalen toch? Zo'n examiner kan best streng zijn.... 

Hiernder mijn commentaar. probeer vooral hfd 5 heel netjes te krijgen. Je hebt al dat materiaal al, dus dat is makkelijk. 

Let wel op: bij jullie CS is de beoordeling heel anders: namelijk Implementatie project: uitvoering 55%, verslag/scriptie 30%, presentatie 15%

Dus je kan ook zeggen dat je je heel erg op de uitvoering en de presentatie gaat richten, maar goed, deze percentages zijn ook maar een aanwijzing en niet hard. 

Groet en succes
maarten

# comments scriptie Pepijn van Wijk 2024-06-10

* abstract
    * prima, alleen zou ik ipv "vector database" iets specifiekers zijn. De database is namelijk niet van belang, maar dat je BM25 ranked keyword search toestaat plus een hybride vorm van lexicaal en semantisch zoeken gebaseerd op embeddings. 
* Title
    * Ik zou specifieker zijn: Iets als opening up archives of videotaped councul meetings notes using Automatic speech and speaker recognition and Retrieval augmented generation.
* zet ajb regelnummers in je latex. Zo is het heel lastig commentaar te geven
* Alinea 2: je zou de situatie bij alles behalve de e1ste en 2de kamer kunnen afzetten tegen de Kamers: hier heb je een mooi transcript van alles wat er gezegd is en daar kan je prachtig in zoeken. Je zou iets vergelijkbaars willen bij de andere , maar dat is onhaalbaar duur: enter tada Pepijn met zijn mooie systeem! 
  * Maak een plaatje van een stukje handelingen. En geef ook de Hierarchishe structuur van agendapunten en daaronder speeches weer (je kan dat ook met een stukkie XML laten zien). Dit is wat je wilt gaan bereiken op een zo geautomatiseerd mogelijke wijze.
  * **Daarnaast** wil je nog snellere **antwoorden** mogelijk maken , en dat doe je met RAG.
* RQs
    * ze staan nu wel mooi in de text maar ik vind een bulleted list, en liefst nog met namen/nummers per deelvraag toch vaak een stuk overzichtelijker. Je kan dan ook lekker terugverwijzen zonder weer die hele vraag te hoeven intypen/lezen.
* Related work
    * Dit mage best wat dieper gaan. Je wilt laten zien dat je bewust bent van andere systemen. Een eerste zoektocht zou <https://scholar.google.nl/scholar?q=automated+speech+recognition+italian+parliament&hl=nl&as_sdt=0&as_vis=1&oi=scholart> kunnen zijn. 
* Backgroun is prima, besteed hier nu niet veel aandacht meer aan: hier scoor je niet veel mee.
* Ik zou My work hernoemen naar "Methods", en chap 5 naar Evaluation.
* Probeer zowel hfd 4 als 5 handig in te delen aan de hand van je onderzoeksvragen. Voor elkke vraag een (sub)sectie. Dat geeft rust en overzicht, vooral ook voor de lezer die er niet inzit (je examinatior bijvoorbeeld).


### Evaluatie

Ik doe als voorbeeld even 5.1.1. Dit is een leuk begin, maar dit moet veel precieser. 

1. In Hfd 4 schrijf je dat je 2 ASR systemen/instellingen ebruikt. OK, en waar gaat dit dan over? Waarom zien we geen cijfers van allebei? 
2. Je moet heel precies zeggen hoe je de annotatie gedaan hebt, over hoeveel stukjes het ging, hoeveel sprkers, hoeveel gemeentes, etc, etc. Je zal moeten overtuigen dat jouw selectie representatief is (dus niet alles van 1 te gekke keurige spreker). 
3. Ik zou een stukje van jouw tekst en heteklfde stukje whiser ASR output in 1 tabel onder elkaar zetten, met in rood de fouten (of zelfs de verschillende typen futen in verschilende kleuren). Kies gewoon iets waar best wat goed gaat maar ook een paar leuk fouten inzitten.
4. Zorg voor een perfecte caption bij Figuur 5.1 (je wilt het aantalminuten en aantal woorden per soort meeting weten (de N)), etc, etc


### tabekl 5.4

Gaaf, maar ook hier veel meer informatie, en zorg dat het niet misleidend is.

**Comment by deboradum** [comment]
Super veel tips, thanks!!

Ik ga ze deze week allemaal doornemen en verbeteren uiteraard! 

Alvast bedankt en je hoort het van me als ik nog vragen heb!

**Comment by deboradum** [comment]
Hi @maartenmarx 

Ik heb een korte vragenlijst gemaakt voor de testers:
https://forms.gle/ULjQZ6uCShdyb1sRA

Ook heb ik nog even snel de andere spreekbeurten gecorrigeerd, na aanleiding van die bug van afgelopen week.

Ik heb Maik een friendly reminder gestuurd en de nieuwe data opgestuurd.

Nu aan de gang met de feeback verwerken! ✍️✍️

Fijne avond!
