### ISSUE TITLE
kleine update 14/06/2024

### ISSUE THREAD

**Issue by deboradum** [deboradum/bachelorThesis#14]
Hi @maartenmarx 

Een kleine update deze week, ik ben voornamelijk bezig geweest met de tips verwerken in m'n thesis, en hier en daar wat videotulen updates wanneer het nodig is. 

Voor zover ik heb getest doet de video het nu online (https://videotulen.wooverheid.nl/#/gemeente/hoekschewaard/vergaderingen/2023/1068571), inclusief de gefixte zoekfunctie en spreker herkenning. Ik heb ook een download transcript knop onder de titel toegevoegd, alleen dit staat nog niet online. Ik heb Maik hiervoor een mailtje gestuurd dus dat zzal in de loop van komende week online komen vermoed ik.

Dit weekend ga ik bezig met de laatste loodjes van de thesis en de presentatie maken.

Het einde nadert! Tot donderdag!

Fijn weekend en groetjes Pepijn

**Comment by deboradum** [comment]
De transcript download functionaliteit staat inmiddels online en werkt!

Ook heb ik de tips verwerkt in de thesis: https://www.overleaf.com/read/ffgqmgpqwfyh#90ebac

En ben ik begonnen met de presentatie. Deze zal ik begin komende week opsturen voor de meeting donderdag. Ik had hier nog wel een vraagje over: wordt er in de presentatie ook verwacht dat ik de evaluatie/ resultaten enzo doorneem? Ik heb het gevoel dat de presentatie dan al gauw (te) lang wordt als ik ook de onderzoeksvragen bespreek, wat essentiele achtergrond informatie, methodologie, evaluatie en conclusie doe. 

Fijn weekend!

groetjes Pepijn

**Comment by maartenmarx** [comment]
Hi @deboradum , Ik heb het in een blogpost gezet: https://wooverheid.nl/2024/06/13/zoeken-in-videotulen-2/

Nee, ik zou de evaluatie heel kort benoemen, maar vooral een minuut of 3-4 een demo geven. Dat is toch heel gaaf wat je gemaakt hebt!
groet
maarten
