### ISSUE TITLE
opzet slides

### ISSUE THREAD

**Issue by maartenmarx** [deboradum/bachelorThesis#15]
Hi @deboradum , hier een opzetje voor je slides voor volgende week vrijdag

1. **Het probleem**
    * lange vergaderingen met veel agendapunten waar een hoop besproken wordt alleen beschikbaar als video.
    * Niet netjes als verslag "wie heeft wat gezegd waarover" zoals bij de Tweede Kamer. (laat 5 tellen een voorbeeld van de handelingen zien) 
    * **Dus** heel lastig en tijdrovend iets terug te vinden of op te zoeken.
    * **Scope** dit speelt bij vrijwel alle gemeentes (343), wateraschappen (20) en provincies (12), zeker eens in de maand
2. **Onze oplossing**
   * Maak met AI **helemaal automatisch** net zo'n transcript waar je snel in kan zoeken, en 
      * direct kan springen naar de relevante plek in de video,
      * of een samenvatting/antwoord krijgt gemaakt met een chatGPT achtige chatbot.
3. **Hoe gaat dat dan?** Kort 1 slide, giga downloaden, ASR en spreker herkenning en je hebt al opdeling in onderwerpen. Chatbot.
4. **Hoe goed werkt het?** Kort 1 slides, alle dingen die je hebt opgemeten. Maar de echte "keuringstest" zit natuurlijk in het gebruik, dus we gaan daar nu naar kijken:
5. Je demo
   * Let kort je "dshboard" uit, met de hieracrchische indeing, en waar je vragen stelt (ga niet in op bm25, hybride, etc, dat is gewoon het oude google deel, en dat andere is het moderne chat deel)
   * Bereid een goede *informatiebehoefte* voor, stel die als zoekvraag (dus met een paar keywoorden) aan de BM25 en spring naar het stukje in de video
   * Stel , misschien wel gewoon dezelfde, vraag als chat-vraag, en dan kunnen de mensen meteen zien dat het wel ergens op slaat/in de buurt zit.
6. Klaar, open vor vragen.

## Zoiets, wat denk je? Lekker snel, en je stipt alles aan van een wetenschappelijk project. Als je dit een beetje uitbouwt heb je meteen ook je presentatie voor je verdediging.

OK, zorg dat je dit morgen hebt uitgewerkt en dan maken we het af. Oefen het ook voor het echie een paar keer, en time het.

Ik zie ernaar uit joh! Groet Maarten

**Comment by deboradum** [comment]
Hey Maarten

Klinkt goed! Ik ga er mee aan de slag. Tot morgen!

Groetjes Pepijn
